index:
    path: '/'
    methods: [GET]
    defaults:
        _controller: 'App\Controller\App\ShowApp'

api_doc:
    resource: 'routes/nelmio_api_doc.yaml'

api_routes:
    prefix: /api/{version}/
    resource: 'routes/api.yaml'
    requirements:
        version: '%api_version%'
    defaults:
        version: '%api_version%'
